Information Center/Controllers/AdminController.cs
using Information_Center.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Information_Center.Controllers
{
    [Authorize(Roles = "Admins")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllStudents()
        {
            var students = _db.Users.Where(u => u.UserType == "Student").ToList();
            return View(students);
        }
        public ActionResult GetAllInstructors()
        {
            var instructors = _db.Users.Where(u => u.UserType == "Instructor").ToList();
            return View(instructors);
        }
    }
}

Information Center/Controllers/CourseController.cs
using Information_Center.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Information_Center.Controllers
{
    [Authorize(Roles ="Instructor")]
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        // GET: Course
         [Authorize(Roles = "Instructor")]
        public ActionResult Index()
        {

            var userId = User.Identity.GetUserId();
            var courses = _db.Courses.Include(c=> c.Instructor).Where(c=> c.InstructorId == userId).ToList();
            return View(courses);
        }

         [Authorize(Roles = "Instructor")]
        public ActionResult CreateCourse()
        {
            //var coure = new Course();
            return View();
        }


        public string AddImge(HttpPostedFileBase ImageFile, string Title)
        {
            string ImagePath = "";
            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                string extension = Path.GetExtension(ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Server.MapPath("~/images/courses/" + Title);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                    ImagePath = "~/images/courses/" + Title + "/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/images/courses/" + Title), fileName);
                    ImageFile.SaveAs(fileName);
                }
            }
            return ImagePath;
        }
         [Authorize(Roles = "Instructor")]
        [HttpPost]
        public ActionResult CreateCourse(Course course)
        {
            if (course == null) return HttpNotFound();
           
            course.ImagePath = AddImge(course.ImageFile, course.Title);
            course.InstructorId = User.Identity.GetUserId();
            _db.Courses.Add(course);
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = course.Id });
        }
        public ActionResult Details(int? id)
        {
            if (id == null) return HttpNotFound();
            var course = _db.Courses.Where(c => c.Id == id).SingleOrDefault();
            if (course == null) return HttpNotFound();
            Session["Course_Id"] = id;
            return View(course);
        }
         [Authorize(Roles = "Instructor")]
        public ActionResult Delete(int? id)
        {
            if (id == null) return HttpNotFound();
            var course = _db.Courses.Where(c => c.Id == id).SingleOrDefault();
            if (course == null) return HttpNotFound();
            deleteImage(course);
            _db.Courses.Remove(course);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public void deleteImage(Course course)
        {
            if (Directory.Exists(Server.MapPath("~/images/courses/" + course.Title)) && System.IO.File.Exists(Server.MapPath("~/images/courses/" + course.Title + "/" + course.ImagePath.Split('/').Last())))
            {


                System.IO.File.Delete(Server.MapPath("~/images/courses/" + course.Title + "/" + course.ImagePath.Split('/').Last()));
                Directory.Delete(Server.MapPath("~/images/courses/" + course.Title));

            }
        }

         [Authorize(Roles = "Instructor")]
        public ActionResult EditForm()
        {
            return View();
        }
         [Authorize(Roles = "Instructor")]
        public ActionResult Edit(int? id)
        {
            if (id == null) return HttpNotFound();
            var course = _db.Courses.Where(c => c.Id == id).SingleOrDefault();
            if (course == null) return HttpNotFound();
            
            return View("EditForm",course);

        }
         [Authorize(Roles = "Instructor")]
        [HttpPost]
        public ActionResult Edit(Course course)
        {
            if (course == null) return HttpNotFound();

            var courseInDb = _db.Courses.Where(c => c.Id == course.Id).SingleOrDefault();
            if (courseInDb == null) return HttpNotFound();
            string oldImgPath = Request.MapPath(courseInDb.ImagePath);
            string oldDirPath = Request.MapPath("~/images/courses/" + courseInDb.Title);
            
            courseInDb.Title = course.Title;
            courseInDb.Description = course.Description;
            if (course.ImageFile != null && course.ImageFile.ContentLength > 0)
            {
                string fileName = Path.GetFileNameWithoutExtension(course.ImageFile.FileName);
                string extension = Path.GetExtension(course.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                //string newDirPath = Server.MapPath("~/images/courses/" + courseInDb.Title);
                //if (!Directory.Exists(newDirPath))
                //{
                //    Directory.CreateDirectory(newDirPath);
                //    //string oldDirPath = Server.MapPath("~/images/courses/" + OldPath.Split('/').Last());
                //    if(Directory.Exists(oldDirPath))
                //    Directory.Move(oldDirPath, newDirPath);
                //    //Directory.Delete(oldDirPath);
                //    courseInDb.ImagePath = "~/images/courses/" + courseInDb.Title + "/" + fileName;
                //    fileName = Path.Combine(Server.MapPath("~/images/courses/" + courseInDb.Title), fileName);
                //    course.ImageFile.SaveAs(fileName);
                //}
                courseInDb.ImagePath = "~/images/courses/" + courseInDb.Title + "/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/images/courses/" + courseInDb.Title), fileName);
                course.ImageFile.SaveAs(fileName);

                if (System.IO.File.Exists(oldImgPath))
                {
                    //System.IO.File.Move("")
                    System.IO.File.Delete(oldImgPath);

                }
                //string newDirPath = Request.MapPath("~/images/courses/" + courseInDb.Title);
                //Directory.Move(oldDirPath, newDirPath);

            }
           
            //courseInDb.ImagePath = course.ImagePath;
            _db.SaveChanges();


            return RedirectToAction("Details", new { id = course.Id});

        }
        
        //[HttpPost]
        public ActionResult Enroll()
        {
            var userId = User.Identity.GetUserId();
            var courseId = (int)Session["Course_Id"];
            var check = _db.Enrollments.Where(e => e.CourseId == courseId && e.StudentId == userId).ToList();
            if(check.Count < 1)
            {
                var enroll = new Enrollment();
                enroll.StudentId = userId;
                enroll.CourseId = courseId;
                enroll.EnrollDate = DateTime.Now;
                _db.Enrollments.Add(enroll);
                ViewBag.Result = "تمت";
            }
            else
            {
                ViewBag.Result = "انت مسجل فيه";

            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = courseId });
        }


    }
}

Information Center/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo&display=swap">
    <title>StudentLogin</title>
    @Styles.Render("~/Content/student-css")
    @Styles.Render("~/Content/student-css/login")
    <meta name="viewport" content="width=device-width" />
    <title>LoginLayout</title>
</head>
<body>
    <div class="overflow"></div>
    <div class="container">
        <div class="logo">
            <a href="@Url.Action("Index","Home")">
                <img src="~/Content/Photo_1625953617841.png" />
            </a>
        </div>
        <h1 style="color:white;">Kh@l!123<br />Mm.01271310939</h1>
        <div class="login-form">
            @RenderBody()
        </div>
    </div>



    <div class="back-home">
        <div class="container">
            <a href="@Url.Action("Index","Home")" class="back-link"><i class="fa fa-arrow-lef"></i>الرجوع للصفحة الرئيسية</a>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

Information Center/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo&display=swap">
    <link rel="stylesheet" href="~/Content/student-css/fonts/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/plugins/aos/css/aos.css" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/adminView")

    @*@Styles.Render("~/Content/plugins/aos/css")*@
    <title>@ViewBag.Title - Information Center</title>
    @Scripts.Render("~/bundles/modernizr")


</head>

<body>
    <div class="sidebar" id="sidebar">
        <div class="sidebar-header">
            <a href="@Url.Action("Index","Home")">
                <div class="sidebar-brand">
                    <!-- <h1><span class="fa fa-github"></span> Hello</h1> -->
                    <img class="logo-png" src="~/images/site/logo.png" alt="">

                </div>
            </a>
            <i class="fa fa-close"></i>
        </div>
        <div class="sidebar-menu">
            <ul>
                <li>
                    <a href="@Url.Action("GetAllStudents", "Admin")" class="@ViewBag.active1"><i class="fa fa-users"></i> الطلاب</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Course")" class="@ViewBag.active2"><i class="fa fa-newspaper-o"></i> المقررات</a>
                </li>
                <li>
                    <a href="@Url.Action("GetAllInstructors", "Admin")" class="@ViewBag.active3"><i class="fa fa-users"></i> المعلمين</a>
                </li>
                <li>
                    <a href="#" id="s" class="@ViewBag.active4"><i class="fa fa-list"></i> الاحداث</a>
                </li>
            </ul>
        </div>
    </div>

    <!-- main content -->
    <div class="main-content" id="main-content">
        <div class="header" id="header">
            <div class="container">
                <div class="content">

                    <div class="header-title">
                        <h1>
                            <span id="nav-toggle" class="fa fa-bars"></span>
                            <a class="header-link" href="@Url.Action("Index","Admin")"> Dashboard </a>
                        </h1>
                    </div>
                    <div class="user-wrapper">
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
        </div>

        <main>

            <div class="container">

                @RenderBody()
            </div>

        </main>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/adminView")
    @*<script src="~/Content/adminView/js/admin.js"></script>*@
   
    @RenderSection("scripts", required: false)
</body>
</html>

Information Center/Views/Shared/_StudentLayout.cshtml
@using Microsoft.AspNet.Identity
@using System.Globalization;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo&display=swap">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/student-css")
    @Styles.Render("~/Content/plugins")
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/plugins")
    <style>
        a:focus, a:hover {
            text-decoration: none;
        }

        a:focus, a:hover {
            text-decoration: none;
        }

        .main-links {
            background: var(--blueColor);
        }

            .main-links ul {
                display: flex;
                justify-content: space-between;
                margin-bottom: 0px;
            }

            .main-links li {
                padding: 10px 0;
                transition: all 0.3s ease;
                width: 100%;
                text-align: center;
            }

                .main-links li:hover, .main-links li.active {
                    background: var(--lightblue);
                }

            .main-links ul li a {
                color: white;
            }
    </style>
</head>

<body>
    @{ var s = DateTime.Now.ToString("dd dddd , MMMM, yyyy", new CultureInfo("ar-AE")); }
    <!-- Header -->
    <div class="container">
        <div class="header">
            <div class="logo">
                <a href="@Url.Action("Index","Home")">
                    <img src="~/Content/Photo_1625953617841.png" />
                </a>
            </div>
            <div>
                @s
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    <!-- End Header -->
    @if (User.IsInRole("Student"))
    {
        <div class="main-links">
            <div class="container">
                <ul>
                    <li class="@ViewBag.active1"><a href="@Url.Action("Index","Student")">My Courses</a></li>
                    <li class="@ViewBag.active2"><a href="">My Materials</a></li>
                    <li class="@ViewBag.active3"><a href="">My Assigments</a></li>
                    <li class="@ViewBag.active4"><a href="">My Grade</a></li>
                </ul>
            </div>
        </div>
    }
    else if (User.IsInRole("Instructor"))
    {
        <div class="main-links">
            <div class="container">
                <ul>
                    <li class="@ViewBag.active1"><a href="@Url.Action("Index","Course")">My Courses</a></li>
                    <li class="@ViewBag.active2"><a href="">My Materials</a></li>
                    <li class="@ViewBag.active3"><a href="">My Assigments</a></li>
                    <li class="@ViewBag.active4"><a href="@Url.Action("GetInstructorStudents","Instructor")">My Students</a></li>


                </ul>
            </div>
        </div>
    }
    <!-- Searching section -->
    <div class="searching-sec">
        <div class="container">
            <div class="search-control">
                <button><i class="fa fa-search"></i></button>
                <input type="search" class="form-control" placeholder="ابحث......." />
            </div>
        </div>
    </div>

    <!-- End Searching section -->

    @RenderBody()
    <!-- Footer -->
    <div class="footer">
        <div class="container">
            <div class="col-md-4 col-sm-2">
                <div class="footer-sec">
                    <h2>Services</h2>
                    <ul>
                        <li><a href="#About-Us">About Us</a></li>
                        <li><a href="">Contact Us</a></li>
                        <li><a href="">Contact Us</a></li>
                        <li><a href="">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-2">
                <div class="footer-sec">
                    <h2>Polices</h2>
                    <ul>
                        <li><a href="">Term of use</a></li>
                        <li><a href="">privecy</a></li>
                        <li><a href="">Refund Policy</a></li>
                        <li><a href="">Billing System</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-2">
                <div class="footer-sec">
                    <h2>qucik access</h2>
                    <ul>
                        <li><a href="">my courses</a></li>
                        <li><a href="">my materials</a></li>
                        <li><a href="">my assigments</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer -->

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/plugins/slick/slick-script.js"></script>
</body>

</html>